services:
  ffmpeg:
    image: jrottenberg/ffmpeg:5.1.2-nvidia2004
    entrypoint: []
    volumes:
      - ${VISIONE_ROOT}:/data
      - ${VISIONE_CACHE}:/cache
    profiles: ["analysis"]
    deploy: &needs_gpu
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  scene-detection: &common
    build: ./analysis/scene-detection
    volumes:
      - ${VISIONE_ROOT}:/data
      - ${VISIONE_CACHE}:/cache
      - ./common:/usr/src/visione:ro
    profiles: ["analysis"]

  objects-colors:
    <<: *common
    build: ./analysis/objects-colors

  objects-mmdet:
    <<: *common
    build: ./analysis/objects-mmdet
    deploy: *needs_gpu

  objects-openimagesv4:
    <<: *common
    build: ./analysis/objects-openimagesv4
    deploy: *needs_gpu

  features-gem:
    <<: *common
    build: ./analysis/features-gem
    shm_size: 2GB
    deploy: *needs_gpu
    profiles: ["features-gem"]
  
  features-clip-openai:
    <<: *common
    build: ./analysis/features-clip
    environment: 
      - FEATURES_NAME=clip-openai
      - MODEL_HANDLE=openai/clip-vit-large-patch14
    deploy: *needs_gpu
    profiles: ["features-clip-openai"]

  features-clip-laion:
    <<: *common
    build: ./analysis/features-clip
    environment:
      - FEATURES_NAME=clip-laion
      - MODEL_HANDLE=laion/CLIP-ViT-H-14-laion2B-s32B-b79K
    deploy: *needs_gpu
    profiles: ["features-clip-laion"]

  features-aladin:
    <<: *common
    build: ./analysis/features-aladin
    deploy: *needs_gpu
    profiles: ["features-aladin"]

  frame-cluster:
    <<: *common
    build: ./analysis/frame-cluster

