services:
  ffmpeg:
    image: jrottenberg/ffmpeg:5.1.2-nvidia2004
    entrypoint: []
    volumes:
      - ${VISIONE_ROOT}:/data
      - ${VISIONE_CACHE}:/cache
    profiles: ["analysis", "ffmpeg"]
    deploy: &needs_gpu
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  scene-detection:
    build: ./analysis/scene-detection
    image: visione/scene-detection
    volumes: &common_volumes
      - ${VISIONE_ROOT}:/data
      - ${VISIONE_CACHE}:/cache
      - ./common:/usr/src/visione:ro
    profiles: ["analysis", "scene-detection"]

  objects-colors:
    build: ./analysis/objects-colors
    image: visione/objects-colors
    volumes: *common_volumes
    profiles: ["analysis", "objects-colors"]

  objects-mmdet:
    build: ./analysis/objects-mmdet
    image: visione/objects-mmdet
    volumes: *common_volumes
    profiles: ["analysis", "objects-mmdet"]
    deploy: *needs_gpu

  objects-openimagesv4:
    build: ./analysis/objects-openimagesv4
    image: visione/objects-openimagesv4
    volumes: *common_volumes
    profiles: ["analysis", "objects-openimagesv4"]
    deploy: *needs_gpu

  features-gem:
    build: ./analysis/features-gem
    image: visione/features-gem
    shm_size: 2GB
    volumes: *common_volumes
    profiles: ["analysis", "features-gem"]
    deploy: *needs_gpu

  features-clip-openai:
    build: ./analysis/features-clip
    image: visione/features-clip
    environment:
      - FEATURES_NAME=clip-openai
      - MODEL_HANDLE=openai/clip-vit-large-patch14
    deploy: *needs_gpu
    volumes: *common_volumes
    profiles: ["analysis", "features-clip-openai"]

  features-clip-laion:
    build: ./analysis/features-clip
    image: visione/features-clip
    environment:
      - FEATURES_NAME=clip-laion
      - MODEL_HANDLE=laion/CLIP-ViT-H-14-laion2B-s32B-b79K
    volumes: *common_volumes
    profiles: ["analysis", "features-clip-laion"]
    deploy: *needs_gpu

  features-aladin:
    build: ./analysis/features-aladin
    image: visione/features-aladin
    volumes: *common_volumes
    profiles: ["analysis", "features-aladin"]
    deploy: *needs_gpu

  frame-cluster:
    build: ./analysis/frame-cluster
    image: visione/frame-cluster
    volumes: *common_volumes
    profiles: ["analysis", "frame-cluster"]

