services:
  router:
    image: nginx:1.23.2
    ports: ["${VISIONE_PORT}:80"]
    env_file: ["${VISIONE_ROOT}/config.env"]
    volumes:
      - ./router:/etc/nginx/templates/
      - ./web-ui:/usr/share/nginx/html:ro
      - ${VISIONE_ROOT}:/data:ro
    depends_on: ["core"]
    profiles: ["query"]

  core:
    build:
      context: ./core
      args:
        - TOMCAT_MANAGER_USER=${VISIONE_USERNAME}
        - TOMCAT_MANAGER_PASS=${VISIONE_PASSWORD}
    expose: ["8080"]
    volumes:
      - ${VISIONE_ROOT}:/data
    profiles: ["query"]
