services:
  router:
    image: nginx:1.23.2
    ports: ["${VISIONE_PORT}:80"]
    environment:
      - VISIONE_VIDEOS_URL
      - VISIONE_RESIZED_VIDEOS_URL
      - VISIONE_FRAMES_URL
      - VISIONE_RESIZED_FRAMES_URL
      - VISIONE_GEM_URL
      - VISIONE_ALADIN_URL
      - VISIONE_CLIP_URL
      - VISIONE_CLIP_INTERNAL_SEARCH_URL
      - VISIONE_CLIP_LAION_URL
      - VISIONE_CLIP_LAION_INTERNAL_SEARCH_URL
    volumes:
      - ./router:/etc/nginx/templates/
      - ./web-ui:/usr/share/nginx/html:ro
      - ${VISIONE_ROOT}:/data:ro
    depends_on: ["core"]
    profiles: ["query"]

  core:
    build:
      context: ./core
      args:
        - TOMCAT_MANAGER_USER=${VISIONE_USERNAME}
        - TOMCAT_MANAGER_PASS=${VISIONE_PASSWORD}
    image: visione/core
    expose: ["8080"]
    volumes:
      - ${VISIONE_ROOT}:/data
    profiles: ["query"]
