services:
  str-object-encoder:
    build: ./index/str-object-encoder
    image: visione/str-object-encoder
    volumes: &common_volumes
      - ${VISIONE_ROOT}:/data
      - ${VISIONE_CACHE}:/cache
      - ./common:/usr/src/visione:ro
    profiles: ["index", "str-object-encoder"]

  str-feature-encoder:
    build: ./index/str-feature-encoder
    image: visione/str-feature-encoder
    volumes: *common_volumes
    profiles: ["query", "index", "str-feature-encoder"]

  lucene-index-manager:
    build: ./index/lucene-index-manager
    image: visione/lucene-index-manager
    volumes: *common_volumes
    profiles: ["index", "lucene-index-manager"]

  faiss-index-manager:
    build: ./index/faiss-index-manager
    image: visione/faiss-index-manager
    volumes: *common_volumes
    profiles: ["query", "index", "faiss-index-manager"]