services:
  str-object-encoder: &common
    build: ./index/str-object-encoder
    image: visione/str-object-encoder
    volumes:
      - ${VISIONE_ROOT}:/data
      - ${VISIONE_CACHE}:/cache
      - ./common:/usr/src/visione:ro
    profiles: ["index"]

  str-feature-encoder:
    <<: *common
    build: ./index/str-feature-encoder
    image: visione/str-feature-encoder
    profiles: ["index", "query"]

  lucene-index-manager:
    <<: *common
    build: ./index/lucene-index-manager
    image: visione/lucene-index-manager

  faiss-index-manager:
    <<: *common
    build: ./index/faiss-index-manager
    image: visione/faiss-index-manager
    profiles: ["index", "query"]