services:
  core:
    build:
      context: ./core
      args:
        - TOMCAT_MANAGER_USER=${TOMCAT_MANAGER_USER}
        - TOMCAT_MANAGER_PASS=${TOMCAT_MANAGER_PASS}
    networks:
      - frontend
      - backend
    ports:
      - "80:8080"  # tomcat is exposed externally on port 80
    volumes:
      - core-index:/data/lucene_index
      - core-thumbs:/data/thumbnails

      # (optional) those are for easy development (no need to rebuild container after modifying code or conf)
      - ./core/root:/usr/local/tomcat/webapps/visione
      - ./core/conf:/conf

  clip:
    image: mesnico/clip2video_visione_webservice
    networks:
      - backend
    expose:
      - "5010"

  mongo:
    image: mongo:5.0.5
    command: --wiredTigerCacheSizeGB 1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_USERNAME}
    networks:
      - backend
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    profiles:
      - devel

  mongo-gui:
    image: mongo-express:0.54.0
    restart: always
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    networks:
      - backend
    ports:
      - "8081:8081"
    profiles:
      - devel


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge


volumes:
  # core lucene index
  core-index:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CORE_INDEX_PATH}

  # core thumbnails
  core-thumbs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CORE_THUMBS_PATH}

  # mongo data
  mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MONGO_DATA_PATH}
