services:
  router:
    image: nginx:1.23.2
    ports: ["80:80"]
    volumes:
      - ./router.conf:/etc/nginx/templates/default.conf.template
      - core-thumbs:/data/thumbnails:ro
    depends_on: ["core", "mongo-gui"]

  core:
    build:
      context: ./core
      args:
        - TOMCAT_MANAGER_USER=${TOMCAT_MANAGER_USER}
        - TOMCAT_MANAGER_PASS=${TOMCAT_MANAGER_PASS}
    depends_on: ["clip", "tern"]
    expose: ["8080"]
    volumes:
      - core-index:/data/lucene_index
      - core-thumbs:/data/thumbnails
      - core-logs:/data/logs

      # (optional) those are for easy development (no need to rebuild container after modifying code or conf)
      - ./core/root:/usr/local/tomcat/webapps/ROOT
      - ./core/conf:/conf

  clip:
    image: mesnico/clip2video_visione_webservice
    ports: ["5010:5010"]
    expose: ["5010"]

  tern:
    image: mesnico/tern_visione_webservice
    ports: ["5000:5000"]
    expose: ["5000"]

  mongo:
    image: mongo:5.0.5
    command: --wiredTigerCacheSizeGB 1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports: ["27017:27017"]
    expose: ["27017"]
    volumes:
      - mongo-data:/data/db
    profiles: ["index"]

  mongo-gui:
    image: mongo-express:0.54.0
    restart: always
    depends_on: ["mongo"]
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_SITE_BASEURL=/mongo
    ports: ["8081:8081"]
    profiles: ["index"]

  det-oiv4:
    build: ./detectors/objects-openimagesv4
    volumes: ["./visione:/usr/src/visione"]
    depends_on: ["mongo"]
    profiles: ["index"]

  feat-gem:
    build: ./feature-extractors/gem
    volumes: ["./visione:/usr/src/visione"]
    depends_on: ["mongo"]
    profiles: ["index"]

  frame-cluster:
    build: ./frame-cluster
    depends_on: ["mongo"]
    profiles: ["index"]


volumes:
  # core lucene index
  core-index:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CORE_INDEX_PATH}

  # core thumbnails
  core-thumbs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CORE_THUMBS_PATH}
  
  # core logs
  core-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CORE_LOGS_PATH}

  # mongo data
  mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MONGO_DATA_PATH}
