services:
  core:
    build:
      context: ./core
      args:
        - TOMCAT_MANAGER_USER=${TOMCAT_MANAGER_USER}
        - TOMCAT_MANAGER_PASS=${TOMCAT_MANAGER_PASS}
    networks:
      - frontend
    ports:
      - "80:8080"  # tomcat is exposed externally on port 80
    volumes:
      - core-index:/data/lucene_index

      # (optional) those are for easy development (no need to rebuild container after modifying code or conf)
      - ./core/root:/usr/local/tomcat/webapps/visione
      - ./core/conf:/conf

volumes:
  # core lucene index
  core-index:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./core/lucene_vbs2022_Lucia

