services:
  router:
    image: nginx:1.23.2
    ports: ["80:80"]
    volumes:
      - ./router.conf:/etc/nginx/templates/default.conf.template
      - ${VISIONE_ROOT}:/data:ro
    depends_on: ["core", "mongo-gui"]

  core:
    build:
      context: ./core
      args:
        - TOMCAT_MANAGER_USER=${USERNAME}
        - TOMCAT_MANAGER_PASS=${PASSWORD}
    depends_on: ["clip", "tern"]
    expose: ["8080"]
    volumes:
      - ${VISIONE_ROOT}:/data

      # (optional) those are for easy development (no need to rebuild container after modifying code or conf)
      - ./core/root:/usr/local/tomcat/webapps/ROOT
      - ./core/conf:/conf

  clip:
    image: mesnico/clip2video_visione_webservice
    ports: ["5010:5010"]
    expose: ["5010"]

  tern:
    image: mesnico/tern_visione_webservice
    ports: ["5000:5000"]
    expose: ["5000"]

  mongo:
    image: mongo:5.0.5
    command: --wiredTigerCacheSizeGB 1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
    ports: ["27017:27017"]
    expose: ["27017"]
    volumes: 
      - "${VISIONE_ROOT}/mongo-data:/data/db"
      - ./mongo-scripts/init.js:/docker-entrypoint-initdb.d/init.js
    profiles: ["index"]

  mongo-gui:
    image: mongo-express:0.54.0
    restart: always
    depends_on: ["mongo"]
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${PASSWORD}
      - ME_CONFIG_SITE_BASEURL=/mongo
    ports: ["8081:8081"]
    profiles: ["index"]

  objects-openimagesv4:
    build: ./analysis/objects-openimagesv4
    volumes:
      - ${VISIONE_ROOT}:/data:ro
      - ./common:/usr/src/visione:ro
    depends_on: ["mongo"]
    profiles: ["index"]

  features-gem:
    build: ./analysis/gem
    volumes:
      - ${VISIONE_ROOT}:/data:ro
      - ./common:/usr/src/visione:ro
    depends_on: ["mongo"]
    profiles: ["index"]

  frame-cluster:
    build: ./analysis/frame-cluster
    depends_on: ["mongo"]
    profiles: ["index"]